enum routes {
  INIT = 'INIT',

  LOGIN = 'LOGIN',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',

  MAIN = 'MAIN',
  PROFILE = 'PROFILE',
  CONTRACTS = 'CONTRACTS',
  INVOICES = 'INVOICES',
  SETTINGS = 'SETTINGS',
}

export default routes;
